resources:
- internal_service_request_role.yaml
- internal_service_request_role_binding.yaml
- internal_service_request_service_account.yaml
- internal_service_service_account_token.yaml
- internal-services.yaml
- https://github.com/konflux-ci/internal-services/config/crd?ref=3a280dcb584a1b6387b54b768e8ec10ad8d46dcd

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-services
